apiVersion: apps/v1
kind: Deployment
metadata:
  name: cab-devsecop-app
  namespace: cab-devsecop-app
  labels:
    app: cab-devsecop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cab-devsecop-app
  template:
    metadata:
      labels:
        app: cab-devsecop-app
    spec:
      containers:
        - name: cab-devsecop-app
          image: jagadeesharathod/cab-devsecops-app:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: dockerhub-secret
---
apiVersion: v1
kind: Service
metadata:
  name: cab-devsecop-service
  namespace: cab-devsecop-app
spec:
  selector:
    app: cab-devsecops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30080
  type: NodePort
