// <auto-generated />
using System;
using CAB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221027052055_ipbind")]
    partial class ipbind
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CAB.Models.CabData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Cab_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ArmyNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ArmyNo");

                    b.Property<string>("Case_Status")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Case_Status");

                    b.Property<string>("ComplaintNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Complaint_No");

                    b.Property<string>("Complaint_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Complaint_Type");

                    b.Property<DateTime>("Dt_Of_Complaint")
                        .HasColumnType("datetime2")
                        .HasColumnName("Dt_Of_Complaint");

                    b.Property<DateTime>("InfoDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("InfoDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Rank");

                    b.Property<DateTime>("Recd_Date_Cab")
                        .HasColumnType("datetime2")
                        .HasColumnName("Recd_Date_Cab");

                    b.Property<string>("Regt")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Regt");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Subject");

                    b.HasKey("Id");

                    b.ToTable("tbl_CabData");
                });

            modelBuilder.Entity("CAB.Models.Upload_dtl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Import_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Uploaded_filename");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Uploaded_By");

                    b.Property<DateTime>("uploaddt")
                        .HasColumnType("datetime2")
                        .HasColumnName("Uploaded_dt");

                    b.HasKey("Id");

                    b.ToTable("tbl_ImportDtls");
                });

            modelBuilder.Entity("CAB.Models.UploadBinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ipaddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_UploadBinding");
                });
#pragma warning restore 612, 618
        }
    }
}
